from __future__ import annotations

from typing import Any, List, Optional, Protocol
from uuid import UUID

from ....domain.models.agent import Agent
from ....domain.models.channel_app import ChannelApp
from ....domain.models.channel_connection import ChannelConnection
from ....domain.models.channel_resolution import ChannelResolution
from ....domain.models.project import Project
from ....domain.models.tenant import Tenant
from ....domain.models.workflow_config import WorkflowConfig


class TenantRepositoryPort(Protocol):
    async def create(self, *, name: str, slug: str) -> Tenant: ...
    async def get_by_id(self, tenant_id: UUID) -> Optional[Tenant]: ...
    async def list(self) -> List[Tenant]: ...
    async def update(self, tenant_id: UUID, **fields: Any) -> Optional[Tenant]: ...
    async def delete(self, tenant_id: UUID) -> bool: ...


class ProjectRepositoryPort(Protocol):
    async def create(self, *, tenant_id: UUID, name: str, slug: str) -> Project: ...
    async def get_by_id(self, project_id: UUID) -> Optional[Project]: ...
    async def list_by_tenant(self, tenant_id: Optional[UUID] = None) -> List[Project]: ...
    async def update(self, project_id: UUID, **fields: Any) -> Optional[Project]: ...
    async def delete(self, project_id: UUID) -> bool: ...


class AgentRepositoryPort(Protocol):
    async def create(
        self,
        *,
        project_id: UUID,
        name: str,
        langflow_flow_id: str,
        config: dict,
        is_default: bool,
    ) -> Agent: ...
    async def get_by_id(self, agent_id: UUID) -> Optional[Agent]: ...
    async def list_by_project(self, project_id: Optional[UUID] = None) -> List[Agent]: ...
    async def update(self, agent_id: UUID, **fields: Any) -> Optional[Agent]: ...
    async def delete(self, agent_id: UUID) -> bool: ...


class WorkflowConfigRepositoryPort(Protocol):
    async def create(
        self,
        *,
        project_id: UUID,
        name: str,
        n8n_workflow_id: str,
        trigger_type: str,
        config: dict,
    ) -> WorkflowConfig: ...
    async def get_by_id(self, workflow_id: UUID) -> Optional[WorkflowConfig]: ...
    async def list_by_project(self, project_id: Optional[UUID] = None) -> List[WorkflowConfig]: ...
    async def update(self, workflow_id: UUID, **fields: Any) -> Optional[WorkflowConfig]: ...
    async def delete(self, workflow_id: UUID) -> bool: ...


class ChannelConnectionRepositoryPort(Protocol):
    async def create(
        self,
        *,
        project_id: UUID,
        agent_id: UUID,
        channel_type: str,
        external_id: str,
        display_name: Optional[str],
        credentials: dict,
        config: dict,
    ) -> ChannelConnection: ...
    async def get_by_id(self, channel_connection_id: UUID) -> Optional[ChannelConnection]: ...
    async def get_by_channel_and_external_id(
        self, channel_type: str, external_id: str
    ) -> Optional[ChannelResolution]: ...
    async def list_by_project(self, project_id: Optional[UUID] = None) -> List[ChannelConnection]: ...
    async def update(self, channel_connection_id: UUID, **fields: Any) -> Optional[ChannelConnection]: ...
    async def delete(self, channel_connection_id: UUID) -> bool: ...


class ChannelAppRepositoryPort(Protocol):
    """
    Credenciales de la App compartida por proveedor (meta/twitter/tiktok) —
    global, no por tenant. `provider` es la clave natural: solo existen 3
    filas posibles, por eso `upsert` en vez de create/update por id.
    """

    async def upsert(self, *, provider: str, credentials: dict, config: dict) -> ChannelApp: ...
    async def get_by_provider(self, provider: str) -> Optional[ChannelApp]: ...
    async def list(self) -> List[ChannelApp]: ...
    async def delete(self, provider: str) -> bool: ...
