FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential curl \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml uv.lock* ./
RUN pip install uv
RUN uv pip install --system --no-cache-dir .

COPY app ./app
COPY api_gateway ./api_gateway
COPY workers ./workers

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

# El CMD se sobreescribe en docker-compose
CMD ["python", "-m", "workers.kafka.inbound.main"]