FROM python:3.12-slim

WORKDIR /app

# Dependencias sistema mínimas
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Copiamos proyecto
COPY pyproject.toml uv.lock* ./
RUN pip install uv

RUN uv pip install --system --no-cache-dir .

COPY api_gateway ./api_gateway

ENV PYTHONUNBUFFERED=1

# CMD ["uvicorn", "api_gateway.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["uvicorn", "api_gateway.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app/api_gateway"]
