from typing import Protocol

class IdempotencyRepositoryPort(Protocol):
    async def try_start(self, message_id: str, workflow_id: str) -> bool: ...
    async def mark_completed(self, message_id: str) -> None: ...
    async def mark_failed(self, message_id: str) -> None: ...
